<?php

namespace AppBundle\Repository;

/**
 * ApplicationConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationConfigRepository extends \Doctrine\ORM\EntityRepository
{
}
